Interns.Presentation/Controllers/DomainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using AutoMapper;
using Interns.Core.Data;
using Interns.Presentation.DTOs;
using Interns.Services.Helpers;
using Interns.Services.IService;
using log4net;
using static System.String;

namespace Interns.Presentation.Controllers
{
    public class DomainController : Controller
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(DomainController));

        private readonly IDomainService domainService;
        public int PageSize = 4;

        public DomainController(IDomainService domain)
        {
            domainService = domain;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Domains(string stringSearch, string sortOrder, string currentFilter, int page = 1)
        {
            Log.Debug("Started getting all the Domains");

            var getDomains = domainService.GetDomains();
            
            SearchingAndPagingViewModel<Domain> model = new SearchingAndPagingViewModel<Domain>
            {
                Collection = getDomains.OrderBy(p=>p.Name).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems =
                            stringSearch == null ? getDomains.Count() :
                                getDomains.Count(s => s.Name.Contains(stringSearch))
                },
                SortingOrder = IsNullOrEmpty(sortOrder) ? "name_desc" : "",
                SearchString = stringSearch
            };
            
            switch (sortOrder)
            {
                case "name_desc":
                    model.Collection = model.Collection.OrderByDescending(s => s.Name);
                    break;
                default:  // Name ascending 
                    model.Collection = model.Collection.OrderBy(s => s.Name);
                    break;
            }

            if (!IsNullOrEmpty(stringSearch))
            {
                model.Collection = domainService.GetDomains().Where(s => s.Name.Contains(stringSearch));
            }

            
            return View(model);
        }
        

        [HttpGet]
        [Route("domain/GetSubDomainByDomain/{domainId}")]
        public ActionResult GetSubDomainsByDomain(int domainId)
        {
            IEnumerable<SubDomain> subDomainsByDomain = new List<SubDomain>();
            Log.Debug($"Getting the adverise with the domain id:{domainId}");

            try
            {
                subDomainsByDomain = domainService.GetSubDomainsByDomain(domainId);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
            }

            return View(subDomainsByDomain);
        }

        [HttpGet]
        [Route("domain/GetAdvertisesByDomain/{domainId}")]
        public ActionResult GetAdvertisesByDomain(int domainId)
        {
            IEnumerable<Advertise> advertisesByDomain = new List<Advertise>();
            Log.Debug($"Getting the adverise with the domain id:{domainId}");

            try
            {
                advertisesByDomain = domainService.GetAdvertisesByDomain(domainId);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return View(advertisesByDomain);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateDomain()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateDomain(Domain domain)
        {
            Log.Debug("Creating new Domain");

            try
            {
                domainService.InsertDomain(domain);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("Domains");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditDomain(int id)
        {
            Domain domain = new Domain();

            Log.Debug($"Getting the user with the id:{id}");
            try
            {
                domain = domainService.GetDomain(id);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return View(domain);
        }

        [HttpPost]
        public ActionResult EditDomain(Domain domain)
        {
            Log.Debug($"Started to update {domain.Name}");

            try
            {
                domainService.UpdateDomain(domain);
                Log.Info($"{domain.Name} was succesfully updated");
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("Domains");
        }

        [HttpGet]
        public ActionResult DeleteDomain(Domain domain)
        {
            Log.Debug($"Deleting {domain.Name}");

            try
            {
                domainService.DeleteDomain(domain);
                Log.Info($"{domain.Name} was deleted succesfully");
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("Domains");
        }
    }
}

Interns.Presentation/Controllers/SubDomainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Interns.Core.Data;
using Interns.Services.Helpers;
using Interns.Services.IService;
using Interns.Services.Models.SelectFK;
using log4net;
using static System.String;

namespace Interns.Presentation.Controllers
{
    public class SubDomainController : Controller
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(SubDomainController));
        private readonly ISubDomainService subDomainService;
        private readonly IDomainService domainService;
        public int PageSize = 10;
        
        public SubDomainController(ISubDomainService subDomain, IDomainService domain)
        {
            subDomainService = subDomain;
            domainService = domain;
        }

        public ActionResult SubDomains(string stringSearch, string sortOrder, string currentFilter, int page = 1)
        {
            Log.Debug("Started getting all the Subdomains");

            var getSubDomains = subDomainService.GetSubDomains();

            SearchingAndPagingViewModel<SubDomain> model = new SearchingAndPagingViewModel<SubDomain>
            {
                Collection = getSubDomains.OrderBy(p => p.Name).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems =
                        stringSearch == null ? getSubDomains.Count() :
                            getSubDomains.Count(s => s.Name.Contains(stringSearch))
                },
                SortingOrder = IsNullOrEmpty(sortOrder) ? "name_desc" : "",
                SearchString = stringSearch
            };

            switch (sortOrder)
            {
                case "name_desc":
                    model.Collection = model.Collection.OrderByDescending(s => s.DomainId);
                    break;
                default:  // Name ascending 
                    model.Collection = model.Collection.OrderBy(s => s.DomainId);
                    break;
            }

            if (!IsNullOrEmpty(stringSearch))
            {
                model.Collection = getSubDomains.Where(s => s.Name.Contains(stringSearch));
            }
            return View(model);
        }

        [HttpGet]
        [Route("domain/GetAdvertisesBySubDomain/{domainId}")]
        public ActionResult GetAdvertisesBySubDomain(int domainId)
        {
            IEnumerable<Advertise> advertisesBySubDomain = new List<Advertise>();
            try
            {
                advertisesBySubDomain = subDomainService.GetAdvertisesBySubDomain(domainId);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return View(advertisesBySubDomain);
        }

        [HttpGet]
        public ActionResult SelectDomain()
        {
            SelectDomainViewModel model = new SelectDomainViewModel();
            model.Domains = domainService.GetDomains();

            return View(model);
        }

        [HttpPost]
        public ActionResult SelectRole(SelectDomainViewModel model)
        {
            SubDomain subDomain = new SubDomain();
            subDomain.DomainId = model.SelectedDomainId;

            return RedirectToAction("CreateSubDomain", new
            {
                subDomain.DomainId
            });
        }


        [HttpGet]
        public ActionResult CreateSubDomain()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSubDomain(SubDomain subDomain, int domainId)
        {
            subDomain.DomainId = domainId;

            Log.Debug("Creating new SubDomain");
            try
            {
                subDomainService.InsertSubDomain(subDomain);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("SubDomains");
        }

        [HttpGet]
        public ActionResult EditSubDomain(int id)
        {
            var subDomain = subDomainService.GetSubDomain(id);
            return View(subDomain);
        }

        [HttpPost]
        public ActionResult EditSubDomain(SubDomain subDomain)
        {
            Log.Debug($"Updating {subDomain.Name}");

            if (ModelState.IsValid)
            {
                try
                {
                    subDomainService.UpdateSubDomain(subDomain);
                    return RedirectToAction("SubDomains");
                }
                catch (Exception e)
                {
                    Log.Error(e.ToString());
                    throw;
                }
            }

            return View(subDomain);
        }

        [HttpGet]
        public ActionResult DeleteSubDomain(SubDomain subDomain)
        {
            Log.Debug($"Deleting {subDomain.Name}");

            try
            {
                subDomainService.DeleteSubDomain(subDomain);
                Log.Info($"{subDomain.Name} was deleted succesfully");
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("SubDomains");
        }
    }
}

Interns.Presentation/Views/SubDomain/CreateSubDomain.cshtml
@model Interns.Core.Data.SubDomain

@{
    ViewBag.Title = "CreateSubDomain";
}

<h2>CreateSubDomain</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SubDomain</h4>
    <hr />

    <div class="form-group">
        <div class="control-label col-md-2 ">
            @Html.DropDownListFor(m => m.DomainId,
                new SelectList(ViewBag.Domain, "Id", "Name"))
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "SubDomains")
</div>

Interns.Presentation/Views/SubDomain/EditSubDomain.cshtml
@model Interns.Core.Data.SubDomain

@{
    ViewBag.Title = "EditSubDomain";
}

<h2>EditSubDomain</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>SubDomain</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.DomainId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "SubDomains")
</div>

Interns.Presentation/Views/SubDomain/GetAdvertisesBySubDomain.cshtml
@model IEnumerable<Interns.Core.Data.Advertise>

@{
    ViewBag.Title = "GetAdvertisesBySubDomain";
}

<h2>@ViewBag.SubDomainName's Advertises</h2>

<p>
    @Html.ActionLink("Create New", "CreateSubDomain")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Details)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DomainId)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DomainId)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditSubDomain", new { id = item.Id }) |
                @Html.ActionLink("Delete", "DeleteSubDomain", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to List", "SubDomains", "SubDomain")
</div>

Interns.Presentation/Views/SubDomain/GetAllSubDomains.cshtml
@model Interns.Services.Helpers.SearchingAndPagingViewModel<Interns.Core.Data.SubDomain>
@using Interns.Presentation.Helper

@{
    ViewBag.Title = "Subdomains";
}

<h2>Subdomains</h2>

@using (Html.BeginForm("GetAllSubDomains", "SubDomain", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("stringSearch", @Model.SearchString)
        <input type="submit" value="Search" />
    </p>
}

<div class="text-right">
    @Html.ActionLink("Sort by Name Descending", "GetAllSubDomains", new { sortOrder = @Model.SortingOrder, currentFilter = @Model.SearchString, page = @Model.PagingInfo.CurrentPage })
</div>

<div class="panel panel-default">
    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th class="text-left">Name</th>
            <th> Go to </th>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <th>Actions</th>
            }
        </tr>

        @foreach (var item in Model.Collection)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Advertises", "GetAdvertisesByDomain", "Domain", new { domainId = item.Id }, null)
                </td>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "EditSubDomain", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "DeleteSubDomain", new { id = item.Id })
                    </td>
                }
            </tr>
        }
    </table>
</div>

<div class="pull-left">
    Page @(Model.PagingInfo.TotalPages < Model.PagingInfo.CurrentPage ? 0 : Model.PagingInfo.CurrentPage) of @Model.PagingInfo.TotalPages

    @if (Model.PagingInfo.TotalPages > 1)
    {
        <div>
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("GetAllSubDomains", new { page = x }))
        </div>
    }
</div>
<br />

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    <div> @Html.ActionLink("Add Subdomain", "CreateSubDomain", null, new { @class = "btn btn-default" }) </div>
}

Interns.Presentation/Views/SubDomain/SelectDomain.cshtml
@model Interns.Services.Models.SelectFK.SelectDomainViewModel
@{
    ViewBag.Title = "Select Domain";
}

<h2>Please choose the Domain</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again.")
        <fieldset>

            <div class="form-group">
                <div class="control-label col-md-2 ">
                    @Html.DropDownListFor(m => m.SelectedDomainId,
                        new SelectList(Model.Domains, "Id", "Name"), "-- Select Domain --")
                </div>
            </div>

            <div class="control-label col-md-2">
                <input type="submit" value="Choose" />
            </div>

        </fieldset>
    </div>
}

Interns.Presentation/Views/SubDomain/SubDomains.cshtml
@model Interns.Services.Helpers.SearchingAndPagingViewModel<Interns.Core.Data.SubDomain>
@using Interns.Presentation.Helper

@{
    ViewBag.Title = "Subdomains";
}

<h2>Subdomains</h2>

@using (Html.BeginForm("SubDomains", "SubDomain", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("stringSearch", @Model.SearchString)
        <input type="submit" value="Search" />
    </p>
}

<div class="text-right">
    @Html.ActionLink("Sort by Name Descending", "SubDomains", new { sortOrder = @Model.SortingOrder, currentFilter = @Model.SearchString, page = @Model.PagingInfo.CurrentPage })
</div>

<div class="panel panel-default">
    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th class="text-left">Name</th>
            <th> Go to </th>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <th>Actions</th>
            }
        </tr>

        @foreach (var item in Model.Collection)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Advertises", "GetAdvertisesByDomain", "Domain", new { domainId = item.Id }, null)
                </td>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "EditSubDomain", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "DeleteSubDomain", new { id = item.Id })
                    </td>
                }
            </tr>
        }
    </table>
</div>

<div class="pull-left">
    Page @(Model.PagingInfo.TotalPages < Model.PagingInfo.CurrentPage ? 0 : Model.PagingInfo.CurrentPage) of @Model.PagingInfo.TotalPages

    @if (Model.PagingInfo.TotalPages > 1)
    {
        <div>
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("SubDomains", new { page = x }))
        </div>
    }
</div>
<br />

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    <div> @Html.ActionLink("Add Subdomain", "CreateSubDomain", null, new { @class = "btn btn-default" }) </div>
}