Interns.Presentation/Controllers/AdvertiseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Interns.Core.Data;
using Interns.Services.Helpers;
using Interns.Services.IService;
using Interns.Services.Models.SelectFK;
using static System.String;
using log4net;

namespace Interns.Presentation.Controllers
{
    public class AdvertiseController : Controller
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(DomainController));
        private readonly IAdvertiseService advertiseService;
        private readonly IDomainService domainService;
        private readonly IUserService userService;
        private readonly ISubDomainService subDomainService;
        public int PageSize = 3;

        public AdvertiseController(IAdvertiseService advertise, IDomainService domain, IUserService user, ISubDomainService subDomain)
        {
            advertiseService = advertise;
            domainService = domain;
            userService = user;
            subDomainService = subDomain;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Advertises(string stringSearch, string sortOrder, string currentFilter, int page = 1)
        {
            Log.Debug("Started getting all the advertises");

            var getAdvertises = advertiseService.GetAdvertises();
            
            SearchingAndPagingViewModel<Advertise> model = new SearchingAndPagingViewModel<Advertise>
            {
                Collection = getAdvertises.OrderBy(p => p.Title).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems =
                        stringSearch == null ? getAdvertises.Count() :
                            getAdvertises.Count(s => s.Title.Contains(stringSearch))
                },
                SortingOrder = IsNullOrEmpty(sortOrder) ? "end_date" : "",
                SearchString = stringSearch
            };

            switch (sortOrder)
            {
                case "end_date":
                    model.Collection = model.Collection.OrderByDescending(s => s.CreateDate);
                    break;
                default:  // Name ascending 
                    model.Collection = model.Collection.OrderBy(s => s.CreateDate);
                    break;
            }

            if (!IsNullOrEmpty(stringSearch))
            {
                model.Collection = getAdvertises.Where(s => s.Title.Contains(stringSearch) || s.User.UserName.Contains(stringSearch) || s.City.Contains(stringSearch));
            }
            
            return View(model);
        }

        [HttpGet]
        public ActionResult SelectAdvertisesForeignKeys()
        {
            SelectAdvertisesFKs setForeignKeys = new SelectAdvertisesFKs();

            setForeignKeys.Users = userService.GetUsers().Where(e => e.Role.Name == "Company");
            setForeignKeys.Domains = domainService.GetDomains();
            setForeignKeys.SubDomains = subDomainService.GetSubDomains();

            return View(setForeignKeys);
        }

        [HttpPost]
        public ActionResult SelectAdvertisesForeignKeys(SelectAdvertisesFKs model)
        {
            Advertise advertise = new Advertise();

            advertise.DomainId = model.SelectedDomainId;
            advertise.UserId = model.SelectedUserId;
            advertise.SubDomainId = model.SelectedSubDomainId;

            return RedirectToAction("CreateAdvertise", new
            {
                advertise.DomainId,
                advertise.UserId,
                advertise.SubDomainId
            });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAdvertise()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateAdvertise(Advertise advertise, int domainId, int userId, int subDomainId)
        {
            advertise.CreateDate = DateTime.Now;
            advertise.DomainId = domainId;
            advertise.UserId = userId;
            advertise.SubDomainId = subDomainId;

            Log.Debug("Creating new Domain");
            
            try
            {
                advertiseService.InsertAdvertise(advertise);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("Advertises");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditAdvertise(int id)
        {
            Advertise advertises = new Advertise();
            Log.Debug($"Getting the advertise with the id:{id}");

            try
            {
                advertises = advertiseService.GetAdvertise(id);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }
            return View(advertises);
        }

        [HttpPost]
        public ActionResult EditAdvertise(Advertise advertise)
        {
            Log.Debug($"Updating {advertise.Title}");

            if (ModelState.IsValid)
            {
                try
                {
                    advertiseService.UpdateAdvertise(advertise);
                    return RedirectToAction("Advertises");
                }
                catch (Exception e)
                {
                    Log.Error(e.ToString());
                    throw;
                }
            }

            return View(advertise);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteAdvertise(Advertise advertise)
        {
            Log.Debug($"Deleting {advertise.Title}");

            try
            {
                advertiseService.DeleteAdvertise(advertise);
            }
            catch (Exception e)
            {
                Log.Error(e.ToString());
                throw;
            }

            return RedirectToAction("Advertises");
        }
    }
}

Interns.Presentation/Views/Advertise/Advertises.cshtml
@using Interns.Presentation.Helper
@model Interns.Services.Helpers.SearchingAndPagingViewModel<Interns.Core.Data.Advertise>

@{
    ViewBag.Title = "Advertises";
}

<a href="@Url.Action("Advertises", "Advertise")">
    <img src="~/Content/internsLogo.png" alt=""/>
</a>

<div style="text-align: center; padding: 30px 0;">
    <h2>
        <a href="/Advertise/Advertises">Advertises</a> |
        <a href="/QA/QAs"> Prepare for a test</a>
    </h2>
</div>
<div style="text-align: center;">
    <strong>
        Find by Title, Company or City
    </strong>
</div>

@using (Html.BeginForm("Advertises", "Advertise", FormMethod.Get))
    {
        <div style="text-align: center; padding: 10px 0 60px 0;">
            @Html.TextBox("stringSearch", @Model.SearchString)

            <input type="submit" value="Search" />
        </div>
    }

<div class="text-right">
    @Html.ActionLink("Sort by Created Date Descending", "Advertises", new { sortOrder = @Model.SortingOrder, currentFilter = @Model.SearchString, page = @Model.PagingInfo.CurrentPage })
</div>

    @foreach (var p in Model.Collection)
    {
        if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            <div class="pull-right">
                @Html.ActionLink("Edit", "EditAdvertise", new { id = p.Id }) |
                @Html.ActionLink("Delete", "DeleteAdvertise", new { id = p.Id })
            </div>
        }
        @Html.Partial("PartialAd", p)

    }

    @if (Model.PagingInfo.TotalPages > 1)
    {
        <div class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("Advertises", new { page = x }))
        </div>
    }

    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <div>
            @Html.ActionLink("Add Advertise", "SelectAdvertisesForeignKeys", null, new { @class = "btn btn-default" })
        </div>
    }

Interns.Presentation/Views/Advertise/CreateAdvertise.cshtml
@model Interns.Services.Models.SelectFK.SelectAdvertisesFKs

@{
    ViewBag.Title = "Create Advertise";
}

<h2>Create Advertise</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Advertise.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Advertise.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Advertise.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Advertise.Details, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Advertise.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Advertise.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Application Deadline", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Advertise.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Advertise.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Advertise.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Advertise.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Advertise.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateAdvertise" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Advertises")
</div>

Interns.Presentation/Views/Advertise/EditAdvertise.cshtml
@model Interns.Core.Data.Advertise

@{
    ViewBag.Title = "EditAdvertise";
}

<h2>Edit Advertise</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @Html.HiddenFor(m=>m.CreateDate)
        @Html.HiddenFor(m=>m.DomainId)
        @Html.HiddenFor(m=>m.UserId)
        @Html.HiddenFor(m=>m.SubDomainId)


        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Advertises")
</div>

Interns.Presentation/Views/Advertise/GetAllAdvertises.cshtml
@using Interns.Presentation.Helper
@model Interns.Services.Helpers.SearchingAndPagingViewModel<Interns.Core.Data.Advertise>

@{
    ViewBag.Title = "Advertises";
}

<a href="@Url.Action("GetAllAdvertises", "Advertise")">
    <img src="~/Content/internsLogo.png" alt=""/>
</a>

<div style="text-align: center; padding: 30px 0;">
    <h2>
        <a href="/Advertise/GetAllAdvertises">Advertises</a> |
        <a href="/QA/GetAllQAs"> Prepare for a test</a>
    </h2>
</div>
<div style="text-align: center;">
    <strong>
        Find by Title, Company or City
    </strong>
</div>

@using (Html.BeginForm("GetAllAdvertises", "Advertise", FormMethod.Get))
    {
        <div style="text-align: center; padding: 10px 0 60px 0;">
            @Html.TextBox("stringSearch", @Model.SearchString)

            <input type="submit" value="Search" />
        </div>
    }

    @foreach (var p in Model.Collection)
    {
        if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            <div class="pull-right">
                @Html.ActionLink("Edit", "EditAdvertise", new { id = p.Id }) |
                @Html.ActionLink("Delete", "DeleteAdvertise", new { id = p.Id })
            </div>
        }
        @Html.Partial("PartialAd", p)

    }

    @if (Model.PagingInfo.TotalPages > 1)
    {
        <div class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("GetAllAdvertises", new { page = x }))
        </div>
    }

    <div class="text-right">
        @Html.ActionLink("Sort by Created Date Descending", "GetAllAdvertises", new { sortOrder = @Model.SortingOrder, currentFilter = @Model.SearchString, page = @Model.PagingInfo.CurrentPage })
    </div>

    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <div>
            @Html.ActionLink("Add Advertise", "SelectAdvertisesForeignKeys", null, new { @class = "btn btn-default" })
        </div>
    }

Interns.Presentation/Views/Advertise/PartialAd.cshtml
@model Interns.Core.Data.Advertise

<div class="well">
    <h3>
        <strong> @Model.Title</strong> - <i> @Model.User.UserName</i>
    </h3>
    
    <div class="lead"><i>@Model.Details</i></div>

    <div class="lead">
        @Model.City
        <span class="pull-right">
            Domain:
            <i>
                @Model.Domain.Name, @Model.SubDomain.Name
            </i>
        </span>
    </div>

    <div class="pull-left label label-primary">Date Created: @Model.CreateDate</div>
    <span class="pull-right label label-primary"> Application Deadline: @Model.EndDate</span>
</div>

Interns.Presentation/Views/Advertise/SelectAdvertisesForeignKeys.cshtml
@model Interns.Services.Models.SelectFK.SelectAdvertisesFKs

@{
    ViewBag.Title = "Create Advertise";
}

<h2>Choose Options</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <span class="control-label col-md-3 ">
                @Html.DropDownListFor(m => m.SelectedDomainId,
                    new SelectList(Model.Domains, "Id", "Name"), "-- Select Domain --")
            </span>
            <span class="control-label col-md-3 ">
                @Html.DropDownListFor(m => m.SelectedUserId,
                    new SelectList(Model.Users, "Id", "UserName"), "--Select User--")
            </span>
            <span class="control-label col-md-3 ">
                @Html.DropDownListFor(m => m.SelectedSubDomainId,
                    new SelectList(Model.SubDomains, "Id", "Name"), "--Select SubDomain--")
            </span>
        </div>
        
        <div class="control-label col-md-2 pull-left">
            <input type="submit" value="Select"/>
        </div>

    </div>
}